//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_ResoutanOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public Materials()
        {
            this.Specification = new HashSet<Specification>();
        }
    
        public int IdMaterials { get; set; }
        public string NameMaterials { get; set; }
        public int IdUnits { get; set; }
        public decimal Price { get; set; }
    
        public virtual Units Units { get; set; }
        public virtual ICollection<Specification> Specification { get; set; }
    }
}
