//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_ResoutanOrders
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class RestouranOrders_10Entities : DbContext
    {
        private static RestouranOrders_10Entities _context;
        public static RestouranOrders_10Entities GetContext()
        
            {
                if (_context == null)
                    _context = new RestouranOrders_10Entities();
                return _context;
            }
        
        public RestouranOrders_10Entities()
            : base("name=RestouranOrders_10Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Materials> Materials { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<SostavOrder> SostavOrder { get; set; }
        public DbSet<Specification> Specification { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Units> Units { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
