//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_ResoutanOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.SostavOrder = new HashSet<SostavOrder>();
        }
    
        public int IdOrders { get; set; }
        public int OrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int IdClients { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<SostavOrder> SostavOrder { get; set; }
    }
}
