//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_ResoutanOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class SostavOrder
    {
        public int IdSostavOrder { get; set; }
        public int IdOrders { get; set; }
        public int IdProducts { get; set; }
        public double Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
