//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_ResoutanOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public int IdSpecification { get; set; }
        public int ProductID { get; set; }
        public int MaterialID { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
