//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_ResoutanOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units
    {
        public Units()
        {
            this.Materials = new HashSet<Materials>();
            this.Products = new HashSet<Products>();
        }
    
        public int IdUnits { get; set; }
        public string NameUnits { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
