//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_ResoutanOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IdUsers { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int IdRoles { get; set; }
        public bool IsBlocked { get; set; }
        public int Attempts { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
